### ISSUE TITLE
Pre-Release Feedback

### ISSUE THREAD

**Issue by NuptupTDOW** [bigianb/jbgda#1]
First, I wanna say that using this with the newest release has been a thrilling fresh wind under my sails. It's very easy to use so far and makes exporting things smooth. However, I did come across a few concerns and wanted to let you know about them so you're aware. 

First of all, I am using a Windows 11 PC running the newest release of JAVA 20.0.1 with release 0.0.1 of the JBGDA Extractor. I'm using a NTSC Version 2.0 dump of Return to Arms and here's the feedback I wrote down while using it for the past hour and a half so far. 

After running the extraction, I noticed the following file types were not extracted, causing only 680 of the 925 BG/DATA files to get extracted. I am not sure if this was intended, but it notably excludes the files which contain a large portion of the model and texture files.

The file types missed by the export are .CNF .DAT .HDR .ICO .LST .SMG .TEX .VA1 .VAG .VAT which make up the missing 245 folders.

Of these that are of particular importance are the EQCACHE.HDR/DAT and/or EQCACHE2.HDR/DAT which contain all of the armor models and textures. I'm not actually sure why both of these exist though since it seems like they contain the exact same things when opened with the BGDA explorer.

Also, the WCACHE.HDR/DAT file which contains the weapon models and textures also doesn't export.

Also, I'm not sure what PICCACHE.HDR/DAT contains, since it didn't export and it also appears empty when using the BGDA explorer, but seeing as it's the last of the .HDR/DAT files, and it's the largest of them all, I imagine it probably has something I'm looking for since the .HDR/DAT files seem to be model/texture focused.

I'm not actually sure what any of the other files that don't export contain, so it might not matter, but I just wanted to direct your attention to this so you can make that call. However, I would assume that out of 245 files, there must be something important in there maybe besides the 4 .HDR/DAT files.

Lastly, I just wanted to ask if you knew where to find the player character models and textures? I figure they might be inside the PICCACHE files, but I also know that most of the other units from the game are in their own folders such as "FIRIONA.LMP" for example.

**Comment by bigianb** [comment]
Good to see it works. I can look at the RTA files a bit more but it will be the weekend. The VA* files are sound files … the last letter is the language. They are just mp4 files concatenated together if I remember correctly.

**Comment by NuptupTDOW** [comment]
Oh gotcha, that makes sense! Do you know what any of the other files are that weren't exported? Besides the HDR/DAT files, since I'm aware of what those are (Except for PICCACHE.HDR/DAT).

**Comment by bigianb** [comment]
pushed a new version.

EQCACHES extract now.  PICCACHE is a different format ... that will take some research.
I also noticed that many of the EQCACHE gltf exported files are broken due to bad json. I'll look at that sometime.

Note a full export now takes a LOOOOONG time (about an hour on a 2017 iMac). Mainly it is the format converters so you may want to provide a file pattern to make it go faster.

**Comment by NuptupTDOW** [comment]
> pushed a new version.
> 
> EQCACHES extract now. PICCACHE is a different format ... that will take some research. I also noticed that many of the EQCACHE gltf exported files are broken due to bad json. I'll look at that sometime.
> 
> Note a full export now takes a LOOOOONG time (about an hour on a 2017 iMac). Mainly it is the format converters so you may want to provide a file pattern to make it go faster.

I noticed the file pattern option when I first tried it out, but I don't actually know what that is. Could you elaborate?

**Comment by bigianb** [comment]
If you enter, say, ‘boots’ then only file names that contain the string
‘boots’ will be converted ( to png, gltf). Speeds things up if you’re only
interested in a given file or item.

Everything get extracted - it only affects the conversions.

**Comment by NuptupTDOW** [comment]
Oh, that's amazing!

Also, I was just wondering if there's any way to convert the level.world files into some 3D file format that would be usable to import into another program. Such as an object file that could be imported?
