### ISSUE TITLE
v0.0.2 Feedback

### ISSUE THREAD

**Issue by NuptupTDOW** [bigianb/jbgda#2]
So, I noticed what you meant about the GLTF files having a bad JSON. When I tried to import them into my 3d model viewer, or into blender there was a "JSON Error, JSON contains infinity" or something to that effect. Also, just because I'm not entirely familiar with the pro's and con's of it, what is the main reason to export as a GLTF instead of how the BGDA exporter does it by exporting them as OBJ's, with their accompanying material and texture files? Do GLTF's work as model and material combined, or what is the benefit to this method?

As for speed of export, I think it only took me about 5 or 10 minutes, I don't exactly remember, but it seems pretty decently quick for what all it's doing. 

I did have a few items work when I opened them in blender, such as the Firiona model with her skeleton and whatnot, but for some reason she way laying face down on the ground in a t-pose instead of a standing t-pose. I'm not sure if this is a result of the export process, or if they designed the models to be laying on their face, but she was the only one I had time to test last night. I will likely test some others tonight to see if it's only her or more.

I also noticed some exported LMP's didn't have a model file that I could find, such as the LMP for Rallos Zek, which is titled "RALOSZEK.LMP" I believe. Maybe I'm missing it, but I couldn't find it anywhere at least. 

I forgot to check if you got the WCACHE.DAT/HDR files to extract, but I imagine they will likely have the same issue as the EQCACHE files where the JSON outputs "Infinity" and causes them to fail.

Lastly, after searching through again, I still wasn't able to find out where the player character models and the interface graphics are stored. I'll keep looking, but I couldn't locate them yet. 

Amazing update though, works like a charm honestly. Just a couple bugs to iron out and it should be really nice! :D

**Comment by bigianb** [comment]
GLTF is just a better format. It can contain animations, material defs etc. You can use sandbox.babylonjs.com in the browser to view them too.
The problem I think is that the anim data has a different format for RTA which I've not properly implmented in jbgda. It will take a few days to port it over from the c#.

Generally Dark Alliance is better supported because I've done more work with those files.

**Comment by NuptupTDOW** [comment]
> GLTF is just a better format. It can contain animations, material defs etc. You can use sandbox.babylonjs.com in the browser to view them too.

Gotcha! That's pretty nice then. I just am not very familiar with the different file types, but yeah, that sounds pretty awesome being able to have everything stored inside a single file type.

> The problem I think is that the anim data has a different format for RTA which I've not properly implmented in jbgda. It will take a few days to port it over from the c#.

Also makes sense. I'm kind of surprised they'd go through the trouble of changing so much between the two games, but I guess we can't really do anything about that except work around their past decisions now.
 
> Generally Dark Alliance is better supported because I've done more work with those files.

Yeah, I mean, it IS in the name of the extractors afterall, what with them being "BGDA" and "jBGDA" lol. So, it's understandable that you've likely spent more time working with them than you have with CoN and RTA.

I appreciate it a lot though that you're willing to put time into this tool. It's a fantastic resource for these kinds of projects, and I hope I'll have something worthwhile to present to you to show that soon enough!

Also, if you'd like to get some updates on how the project is going, there are two CoN/RTA discords that I post updates to pretty frequently. There's the (Un)official CoN/RTA discord that is tied to the Subreddit where the majority of the members are. I post updates there in the custom content channel and screenshots channel. Then, there's the "Remaking Champions" discord which is focused entirely on the project of remaking them and upscaling the old versions (if we can figure it out). So, if you'd like to be a part of either of those, I can put a link to them here when I get access to my phone.

**Comment by bigianb** [comment]
RTA animations in gltf export files look better now. Probably better for this to be in discussions as it's not really an issue.
Let me know what files you find issues with and I'll look into them.

Regarding the model orientation - that's just how the game stores them. Its concept for which of x,y,z is up is different than blender. It's simple enough to rotate the model in a modelling tool.
